version: '3.7'
services:

  api:
    build:
      context: .
      target: ohs-api
    image: ohs-api
    restart: always
    environment:
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      REDIS_HOST: ${REDIS_HOST}

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}

  redis-server:
    image: redis:latest
    restart: always

  load-balancer:
    build:
      context: .
      target: load-balancer
    image: load-balancer
    restart: always
    ports:
      - 8000:8000

volumes:
  mongo-data:
