version: "3.7"
services:
  api:
    build: .
    image: ohs-api
    restart: always
    ports:
      - 8000:8000
    environment:
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MYSQL_PASSWORD}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_DATABASE: ${MYSQL_DATABASE}

volumes:
  mongodb-data:
